
export default function HowItWorks() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12 md:py-16">
      <div className="text-xs font-medium text-brand uppercase tracking-wide mb-2">Guide</div>
      <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-4">How EdilPlay works</h1>
      <p className="text-text-muted text-lg mb-12">
        Built for the diaspora. Powered by real quantum physics. Verified by you.
      </p>

      <div className="space-y-8">
        {[
          { n: "01", t: "Buy a ticket", d: "Sign up, choose an active draw, and pay using Botim, bank transfer, or Telebirr. We give you a unique reference code — include it in your transfer note." },
          { n: "02", t: "Get verified", d: "Upload your payment receipt. Our admin team verifies it within 24 hours and issues your ticket. You'll receive SMS and email confirmation." },
          { n: "03", t: "Quantum draw", d: "When the draw closes, we fetch true randomness from the Australian National University's quantum lab — randomness generated by quantum vacuum fluctuations. This selects the winning ticket." },
          { n: "04", t: "Verify the result yourself", d: "After each draw, we publish the quantum seed, the algorithm, and the math. You can re-run it independently and confirm the winner. No black boxes." },
          { n: "05", t: "Win & receive your prize", d: "Winners are notified immediately. We verify your ID, arrange logistics, and deliver your prize. Cars and houses are handed over in Addis Ababa with full legal paperwork." },
        ].map((step) => (
          <div key={step.n} className="bg-white border border-border rounded-xl p-6 hover:border-border-strong transition">
            <div className="flex items-start gap-5">
              <div className="flex-shrink-0 w-10 h-10 bg-brand-light text-brand font-semibold rounded-md flex items-center justify-center text-sm">
                {step.n}
              </div>
              <div>
                <h3 className="text-xl font-semibold mb-2">{step.t}</h3>
                <p className="text-text-muted leading-relaxed">{step.d}</p>
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-12 bg-brand-light border border-brand/20 rounded-xl p-6">
        <h3 className="font-semibold mb-2">Why quantum randomness?</h3>
        <p className="text-text-muted text-sm leading-relaxed">
          Traditional random number generators are deterministic — they look random but follow a formula. Quantum randomness comes from physically unpredictable events at the subatomic level. It's the only "true" randomness known to science, and it makes every EdilPlay draw mathematically impossible to rig.
        </p>
      </div>
    </div>
  );
}
